package br.org.soujava.schema.webservice.wsdl._1_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-03-21T12:03:27.193+01:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://schema.soujava.org.br/webservice/wsdl/1.1", name = "esbWebService")
@XmlSeeAlso({br.org.soujava.schema.webservice.wsdl._1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EsbWebService {

    @WebResult(name = "WebServiceInvocationResult", targetNamespace = "http://schema.soujava.org.br/webservice/wsdl/1.1", partName = "parameters")
    @WebMethod
    public br.org.soujava.schema.webservice.wsdl._1.WebServiceInvocationResult postEsbMessage(
        @WebParam(partName = "postEsbMessageRequest", name = "xml", targetNamespace = "http://schema.soujava.org.br/webservice/wsdl/1.1")
        java.lang.String postEsbMessageRequest
    );
}
